/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ShopImport } from './routes/shop'
import { Route as RegisterImport } from './routes/register'
import { Route as OrdersImport } from './routes/orders'
import { Route as LoginImport } from './routes/login'
import { Route as CartImport } from './routes/cart'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const ShopLazyImport = createFileRoute('/shop')()
const RegisterLazyImport = createFileRoute('/register')()
const OrdersLazyImport = createFileRoute('/orders')()
const LoginLazyImport = createFileRoute('/login')()
const CartLazyImport = createFileRoute('/cart')()
const AdminLazyImport = createFileRoute('/admin')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ShopLazyRoute = ShopLazyImport.update({
  path: '/shop',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/shop').then((d) => d.Route))

const RegisterLazyRoute = RegisterLazyImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/register').then((d) => d.Route))

const OrdersLazyRoute = OrdersLazyImport.update({
  path: '/orders',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/orders').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login').then((d) => d.Route))

const CartLazyRoute = CartLazyImport.update({
  path: '/cart',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cart').then((d) => d.Route))

const AdminLazyRoute = AdminLazyImport.update({
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLazyImport
      parentRoute: typeof rootRoute
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersLazyImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterLazyImport
      parentRoute: typeof rootRoute
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminLazyRoute
  '/cart': typeof CartLazyRoute
  '/login': typeof LoginLazyRoute
  '/orders': typeof OrdersLazyRoute
  '/register': typeof RegisterLazyRoute
  '/shop': typeof ShopLazyRoute
}

interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminLazyRoute
  '/cart': typeof CartLazyRoute
  '/login': typeof LoginLazyRoute
  '/orders': typeof OrdersLazyRoute
  '/register': typeof RegisterLazyRoute
  '/shop': typeof ShopLazyRoute
}

interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminLazyRoute
  '/cart': typeof CartLazyRoute
  '/login': typeof LoginLazyRoute
  '/orders': typeof OrdersLazyRoute
  '/register': typeof RegisterLazyRoute
  '/shop': typeof ShopLazyRoute
}

interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/login'
    | '/orders'
    | '/register'
    | '/shop'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/cart' | '/login' | '/orders' | '/register' | '/shop'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/login'
    | '/orders'
    | '/register'
    | '/shop'
  fileRoutesById: FileRoutesById
}

interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AdminLazyRoute: typeof AdminLazyRoute
  CartLazyRoute: typeof CartLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  OrdersLazyRoute: typeof OrdersLazyRoute
  RegisterLazyRoute: typeof RegisterLazyRoute
  ShopLazyRoute: typeof ShopLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AdminLazyRoute: AdminLazyRoute,
  CartLazyRoute: CartLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  OrdersLazyRoute: OrdersLazyRoute,
  RegisterLazyRoute: RegisterLazyRoute,
  ShopLazyRoute: ShopLazyRoute,
}

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/cart",
        "/login",
        "/orders",
        "/register",
        "/shop"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx"
    },
    "/cart": {
      "filePath": "cart.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/orders": {
      "filePath": "orders.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/shop": {
      "filePath": "shop.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
